# Generated by Django 5.1.3 on 2024-12-01 08:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pdf_engine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "ACTIVE"), (1, "INACTIVE")],
                        db_index=True,
                        default=0,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("default", models.BooleanField(default=False)),
                ("style_json", models.JSONField()),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
